import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { execFileSync } from "node:child_process";
const root = process.cwd();
if (execFileSync("git", ["branch", "--show-current"], { encoding: "utf8" }).trim() !== "m35-terrain-movement-query") throw new Error("wrong branch");

patch("src/shared/perfMetrics.ts", (t) => after(t, '  "movementDistanceSum",', '  "terrainMovementSampleCount",\n  "terrainMovementCostSum",\n  "terrainFrictionSum",\n  "terrainDragSum",'));
patch("src/render/pixiRenderer.ts", (t) => {
  t = after(t, '    metrics.record("movementDistanceSum", frame.movementMetrics.distanceAccumulated);', '    metrics.record("terrainMovementSampleCount", frame.movementMetrics.terrainMovementSampleCount);\n    metrics.record("terrainMovementCostSum", frame.movementMetrics.terrainMovementCostSum);\n    metrics.record("terrainFrictionSum", frame.movementMetrics.terrainFrictionSum);\n    metrics.record("terrainDragSum", frame.movementMetrics.terrainDragSum);');
  return t.replace('        movementIntegratedCount: snapshot.values.movementIntegratedCount,\n        deathsThisStep: snapshot.values.deathsThisStep,', '        movementIntegratedCount: snapshot.values.movementIntegratedCount,\n        terrainMovementSampleCount: snapshot.values.terrainMovementSampleCount,\n        terrainMovementCostSum: snapshot.values.terrainMovementCostSum,\n        terrainFrictionSum: snapshot.values.terrainFrictionSum,\n        terrainDragSum: snapshot.values.terrainDragSum,\n        deathsThisStep: snapshot.values.deathsThisStep,');
});
patch("src/render/debugOverlay.ts", (t) => {
  t = t.replace('  readonly movementIntegratedCount: number;\n  readonly obstacleResponseMs: number;', '  readonly movementIntegratedCount: number;\n  readonly terrainMovementSampleCount: number;\n  readonly terrainMovementCostSum: number;\n  readonly terrainFrictionSum: number;\n  readonly terrainDragSum: number;\n  readonly obstacleResponseMs: number;');
  t = after(t, '    movementIntegratedCount: createValueRow(root, "integrated"),', '    terrainMovementSampleCount: createValueRow(root, "terrain move samples"),\n    terrainMovementCostSum: createValueRow(root, "terrain move cost"),\n    terrainFrictionSum: createValueRow(root, "terrain friction"),\n    terrainDragSum: createValueRow(root, "terrain drag"),');
  return after(t, '    rows.movementIntegratedCount.textContent = formatInt(snapshot.movementIntegratedCount);', '    rows.terrainMovementSampleCount.textContent = formatInt(snapshot.terrainMovementSampleCount);\n    rows.terrainMovementCostSum.textContent = formatDecimal(snapshot.terrainMovementCostSum);\n    rows.terrainFrictionSum.textContent = formatDecimal(snapshot.terrainFrictionSum);\n    rows.terrainDragSum.textContent = formatDecimal(snapshot.terrainDragSum);');
});

write("docs/integration_m35.md", `# m35 integration: terrain movement query\n\nMilestone 35 connects the terrain query API to movement only.\n\n## Implementation\n\n- \`stepMovement()\` accepts optional \`terrain: TerrainLayer\`.\n- Agents sample terrain at their current position before movement integration.\n- Terrain drag is added to agent drag.\n- Terrain friction and movement cost modulate effective max speed.\n- Movement energy cost is scaled by terrain movement cost.\n- Demo simulation passes its existing terrain layer into movement.\n- Debug overlay exposes terrain movement sample, cost, friction, and drag metrics.\n\n## Acceptance\n\n- \`npm run test:terrain-movement-query\`\n- \`npm run test\`\n- \`npm run build\`\n\n## Explicitly not changed\n\n- no terrain editor\n- no terrain resource integration\n- no terrain sensor integration\n- no fluid field\n- no controller/brain work\n`);

patch("README.md", (t) => t.replaceAll("m34", "m35").replaceAll("milestone.34", "milestone.35").replace("terrain Pixi debug render layer with overlay metrics.", "terrain Pixi debug render layer with overlay metrics;\n- terrain movement query integration using material friction, drag, and movement cost.").replace("npm run test:terrain-debug-render-layer\n", "npm run test:terrain-debug-render-layer\nnpm run test:terrain-movement-query\n").replace("docs/integration_m35.md` — current terrain debug render layer milestone", "docs/integration_m35.md` — current terrain movement query milestone"));
patch("docs/roadmap.md", (t) => t.replaceAll("m34", "m35").replaceAll("milestone.34", "milestone.35").replace("terrain Pixi debug render layer with overlay metrics.", "terrain Pixi debug render layer with overlay metrics.\n\nm35 shipped: terrain movement query integration using material friction, drag, and movement cost.").replace("terrain query API used by movement, sensors, spawning, and reproduction;", "terrain query API used by movement;\n- later terrain query integration for resources, sensors, spawning, and reproduction;"));
patch("docs/architecture_tracks.md", (t) => t.replace("Current status: m34.", "Current status: m35.").replace("movement/resource/sensor query integration, tests", "movement query integration, later resource/sensor query integration, tests"));
patch("docs/milestones.md", (t) => t.replace("Compact milestone index through m34.", "Compact milestone index through m35.").replace("| m34 | Terrain Pixi debug render layer with overlay metrics. | complete |", "| m34 | Terrain Pixi debug render layer with overlay metrics. | complete |\n| m35 | Terrain movement query integration using material friction, drag, and movement cost. | complete |").replaceAll("- m35: terrain query integration into movement/resource/sensor systems.", "- m36: terrain resource-affinity integration."));
patch("scripts/test-repo-status.mjs", (t) => t.replaceAll("milestone.34", "milestone.35").replaceAll("m34", "m35").replaceAll("integration_m34", "integration_m35").replaceAll("terrain debug render layer", "terrain movement query"));
patch("scripts/test-roadmap-status.mjs", (t) => t.replaceAll("milestone.34", "milestone.35").replaceAll("m34", "m35").replaceAll("integration_m34", "integration_m35").replace("terrain Pixi debug render layer", "terrain movement query integration").replace("pixiRenderer must expose terrain layer render function", "movement must sample terrain"));
patch("scripts/test-demo-integration.mjs", (t) => {
  t = t.replaceAll("milestone.34", "milestone.35").replaceAll("m34", "m35");
  if (!t.includes('scripts/test-terrain-movement-query.mjs')) t = t.replace('const terrainDebugRenderLayerTest = readText("scripts/test-terrain-debug-render-layer.mjs");', 'const terrainDebugRenderLayerTest = readText("scripts/test-terrain-debug-render-layer.mjs");\nconst terrainMovementQueryTest = readText("scripts/test-terrain-movement-query.mjs");');
  if (!t.includes('packageJson.scripts["test:terrain-movement-query"]')) t = t.replace('assert(terrainDebugRenderLayerTest.includes("terrain debug render layer tests passed"), "terrain debug render layer test must expose pass token.");', 'assert(terrainDebugRenderLayerTest.includes("terrain debug render layer tests passed"), "terrain debug render layer test must expose pass token.");\nassert(packageJson.scripts["test:terrain-movement-query"] === "node scripts/test-terrain-movement-query.mjs", "package.json must expose test:terrain-movement-query.");\nassert(packageJson.scripts.test.includes("test:terrain-movement-query"), "npm run test must include terrain movement query test.");\nassert(perfMetrics.includes("terrainMovementSampleCount"), "perf metrics must expose terrainMovementSampleCount.");\nassert(pixiRenderer.includes("terrainMovementCostSum"), "pixiRenderer must record terrain movement cost metric.");\nassert(debugOverlay.includes("terrain move samples"), "debugOverlay must expose terrain movement labels.");\nassert(terrainMovementQueryTest.includes("terrain movement query tests passed"), "terrain movement query test must expose pass token.");');
  return t;
});

function read(p){return readFileSync(join(root,p),"utf8").replaceAll("\r\n","\n")}
function write(p,t){const f=join(root,p); mkdirSync(dirname(f),{recursive:true}); writeFileSync(f,t,"utf8")}
function patch(p,fn){write(p,fn(read(p)))}
function after(t,a,i){return t.includes(i)?t:t.replace(a,a+"\n"+i)}
